# 机器人配置
bot:
  # 启用的机器人账号
  # 只有这些账号接收到的消息才会被处理
  bot-accounts:
    - 123456
    - 789012

  # 启用的群号
  # 只有这些群接收到的消息才会被处理
  group-ids:
    - 123456
    - 789012

  # QQ上的绑定命令前缀
  add-bind-command: "添加绑定"

  # QQ上的确认绑定前缀
  confirm-bind-command: "确认绑定"

  # 绑定确认码长度
  confirm-code-length: 6